### ISSUE TITLE
Missing icon in titlebar

### ISSUE THREAD

**Issue by MattSturgeon** [MattSturgeon/OpenBoardView#3]
At some point down the line the titlebar icon seems to have gone missing!

TODO
- [x] Investigate

**Comment by inflex** [comment]
Do we create a new icon from scratch?  Something good?

**Comment by MattSturgeon** [comment]
> Do we create a new icon from scratch? Something good?

Have thought about it; I'm _ok_ with gimp and inkscape

**Comment by inflex** [comment]
I'd go with Inkscape perhaps?  I use it a fair bit; depends on what we're trying to do, usually clean/simple works well enough?

**Comment by MattSturgeon** [comment]
Agree

**Comment by MattSturgeon** [comment]
Fixed the missing icon in 14c084fe6e5696f18702128218a4a94ded52cf85. Turns out GLFW will load it for us if we declare it as `GLFW_ICON` in the .rc file.
